name: Lint Markdown

on:
  pull_request:
  push:
    paths:
      - '**/*.md'
      - '.github/**'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run markdownlint
        uses: davidanson/markdownlint-action@v1
        with:
          config: |
            default: true
